platform :ios, '11.0'
target "TreeSapIOS" do
  pod 'CSVImporter'
  pod 'Charts'
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'KeyboardAvoidingView'
  pod 'ImageSlideshow'
  pod 'SearchTextField'
  pod 'SideMenu'
  pod 'ReachabilitySwift'
end 
target "TreeSapIOSTests" do
	pod 'CSVImporter'
  pod 'Charts'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'KeyboardAvoidingView'
  pod 'ImageSlideshow'
  pod 'SearchTextField'
  pod 'SideMenu'
  pod 'ReachabilitySwift'
end
target "TreeSapIOSUITests" do
  pod 'CSVImporter'
  pod 'Charts'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'KeyboardAvoidingView'
  pod 'ImageSlideshow'
  pod 'SearchTextField'
  pod 'SideMenu'
  pod 'ReachabilitySwift'
end
