//
//  TreeNames.swift
//  TreeSapIOS
//
//  Created by Jonathan Chaffer in Summer 2019.
//  Copyright © 2019 Hope CS. All rights reserved.
//

class TreeNames {
    static let nameMap = [
        "American Basswood": "",
        "American Beech": "Fagus grandifolia",
        "American Chestnut": "",
        "American Elm": "Ulmus americana",
        "American Sweetgum": "Liquidambar styraciflua",
        "American Sycamore": "Platanus occidentalis",
        "Austrian Pine": "",
        "Autumn Blaze Maple": "Acer x freemanii",
        "Balsam Fir": "Abies balsamea",
        "Bitternut Hickory": "",
        "Black Ash": "",
        "Black Birch": "",
        "Black Locust": "",
        "Black Maple": "Acer nigrum",
        "Black Poplar": "",
        "Black Tupelo": "",
        "Black Walnut": "Juglans nigra",
        "Black Willow": "",
        "Blue Spruce": "",
        "Boxelder": "",
        "Bur Oak": "",
        "Butternut": "",
        "Callery Pear": "",
        "Cherry Plum": "",
        "Chinese Privet": "",
        "Colorado Blue Spruce": "Picea pungens",
        "Common Chokecherry": "",
        "Common Juniper": "Juniperus communis",
        "Crimson King Maple": "Acer platanoides",
        "Dawn Redwood": "Metasequoia glyptostroboides",
        "Eastern Red Cedar": "",
        "Eastern Redbud": "",
        "Eastern White Pine": "",
        "European Alder": "",
        "European Beech": "Fagus sylvatica",
        "European Hornbeam": "",
        "Flowering Dogwood": "",
        "Freeman Maple": "",
        "Ginkgo": "Ginkgo biloba",
        "Green Ash": "",
        "Hedge Maple": "",
        "Honeylocust": "Gleditsia triacanthos",
        "Japanese Flower Crabapple": "",
        "Japanese Flowering Cherry": "",
        "Japanese Maple": "",
        "Japanese Tree Lilac": "",
        "Japanese Zelkova": "",
        "Katsura Tree": "",
        "Littleleaf Linden": "",
        "London Planetree": "",
        "Mountain Maple": "",
        "Mountain Silverbell": "",
        "Northern Hackberry": "",
        "Northern Red Oak": "",
        "Norway Maple": "Acer platanoides",
        "Norway Spruce": "",
        "Ohio Buckeye": "Aesculus glabra",
        "Paper Birch": "Betula papyrifera",
        "Pawpaw": "",
        "Pin Oak": "",
        "Planetree Maple": "Acer pseudoplatanus",
        "Red Birch": "Betula occidentalis",
        "Red Maple": "",
        "Red Oak": "Quercus rubra",
        "Red Pine": "Pinus resinosa",
        "River Birch": "",
        "Rock Elm": "",
        "Rose-Of-Sharon": "",
        "Scots Pine": "",
        "Siberian Elm": "",
        "Silver Linden": "",
        "Silver Maple": "Acer saccharinum",
        "Slippery Elm": "",
        "Southern Catalpa": "",
        "Staghorn Sumac": "",
        "Striped Maple": "",
        "Sugar Maple": "Acer saccharum",
        "Swamp White Oak": "",
        "Sweet Cherry": "",
        "Sweet Crabapple": "",
        "Sweetgum": "",
        "Sycamore Maple": "",
        "Tulip Tree": "",
        "White Ash": "",
        "White Oak": "Quercus alba",
        "White Spruce": "",
        "Wych Elm": "",
        "Yellow poplar": "Liriodendron tulipifera"
    ]
}
