//
//  TreeNames.swift
//  TreeSapIOS
//
//  Created by Jonathan Chaffer in Summer 2019.
//  Copyright © 2019 Hope CS. All rights reserved.
//

class TreeNames {
    static let nameMap = [
        "American Basswood": "Tilia americana",
        "American Beech": "Fagus grandifolia",
        "American Chestnut": "Castanea dentata",
        "American Elm": "Ulmus americana",
        "American Sweetgum": "Liquidambar styraciflua",
        "American Sycamore": "Platanus occidentalis",
        "Austrian Pine": "Pinus nigra",
        "Autumn Blaze Maple": "Acer x freemanii",
        "Balsam Fir": "Abies balsamea",
        "Bitternut Hickory": "Carya cordiformis",
        "Black Ash": "Fraxinus nigra",
        "Black Birch": "Betula lenta",
        "Black Locust": "Robinia pseudoacacia",
        "Black Maple": "Acer nigrum",
        "Black Poplar": "Populus nigra",
        "Black Tupelo": "Nyssa sylvatica",
        "Black Walnut": "Juglans nigra",
        "Black Willow": "Salix nigra",
        "Blue Spruce": "Picea pungens",
        "Boxelder": "Acer negundo",
        "Bur Oak": "Quercus macrocarpa",
        "Butternut": "Juglans cinerea",
        "Callery Pear": "Pyrus calleryana",
        "Cherry Plum": "Prunus cerasifera",
        "Chinese Privet": "Ligustrum sinense",
        "Colorado Blue Spruce": "Picea pungens",
        "Common Chokecherry": "Prunus virginiana",
        "Common Juniper": "Juniperus communis",
        "Crimson King Maple": "Acer platanoides",
        "Dawn Redwood": "Metasequoia glyptostroboides",
        "Eastern Red Cedar": "Juniperus virginiana",
        "Eastern Redbud": "Cercis canadensis",
        "Eastern White Pine": "Pinus strobus",
        "European Alder": "Alnus glutinosa",
        "European Beech": "Fagus sylvatica",
        "European Hornbeam": "Carpinus betulus",
        "Flowering Dogwood": "Cornus florida",
        "Freeman Maple": "Acer freemanii",
        "Ginkgo": "Ginkgo biloba",
        "Green Ash": "Fraxinus pennsylvanica",
        "Hedge Maple": "Acer campestre",
        "Honeylocust": "Gleditsia triacanthos",
        "Japanese Flower Crabapple": "Malus floribunda",
        "Japanese Flowering Cherry": "Prunus serrulata",
        "Japanese Maple": "Acer palmatum",
        "Japanese Tree Lilac": "Syringa reticulata",
        "Japanese Zelkova": "Zelkova serrata",
        "Katsura Tree": "Cercidiphyllum japonicum",
        "Littleleaf Linden": "Tilia cordata",
        "London Planetree": "Platanus x acerifolia",
        "Mountain Maple": "Acer spicatum",
        "Mountain Silverbell": "Halesia tetraptera",
        "Northern Hackberry": "Celtis occidentalis",
        "Northern Red Oak": "Quercus rubra",
        "Norway Maple": "Acer platanoides",
        "Norway Spruce": "Picea abies",
        "Ohio Buckeye": "Aesculus glabra",
        "Paper Birch": "Betula papyrifera",
        "Pawpaw": "Asimina triloba",
        "Pin Oak": "Quercus palustris",
        "Planetree Maple": "Acer pseudoplatanus",
        "Red Birch": "Betula occidentalis",
        "Red Maple": "Acer rubrum",
        "Red Oak": "Quercus rubra",
        "Red Pine": "Pinus resinosa",
        "River Birch": "Betula nigra",
        "Rock Elm": "Ulmus thomasii",
        "Rose-Of-Sharon": "Hibiscus syriacus",
        "Scots Pine": "Pinus sylvestris",
        "Siberian Elm": "Ulmus pumila",
        "Silver Linden": "Tilia tomentosa",
        "Silver Maple": "Acer saccharinum",
        "Slippery Elm": "Ulmus rubra",
        "Southern Catalpa": "Catalpa bignonioides",
        "Staghorn Sumac": "Rhus typhina",
        "Striped Maple": "Acer pensylvanicum",
        "Sugar Maple": "Acer saccharum",
        "Swamp White Oak": "Quercus bicolor",
        "Sweet Cherry": "Prunus avium",
        "Sweet Crabapple": "Malus coronaria",
        "Sweetgum": "Liquidambar styraciflua",
        "Sycamore Maple": "Acer pseudoplatanus",
        "Tulip Tree": "Liriodendron tulipifera",
        "White Ash": "Fraxinus americana",
        "White Oak": "Quercus alba",
        "White Spruce": "Picea glauca",
        "Wych Elm": "Ulmus glabra",
        "Yellow poplar": "Liriodendron tulipifera",
        "Yew": "Taxus baccata"
    ]
}
