//
//  TreeNames.swift
//  TreeSapIOS
//
//  Created by Jonathan Chaffer in Summer 2019.
//  Copyright © 2019 Hope CS. All rights reserved.
//

class TreeNames {
    static let nameMap = [
        "American Basswood": "",
        "American Beech": "",
        "American Chestnut": "",
        "American Elm": "",
        "American Sycamore": "",
        "Austrian Pine": "",
        "Balsam Fir": "",
        "Bitternut Hickory": "",
        "Black Ash": "",
        "Black Birch": "",
        "Black Locust": "",
        "Black Maple": "",
        "Black Poplar": "",
        "Black Tupelo": "",
        "Black Walnut": "",
        "Black Willow": "",
        "Blue Spruce": "",
        "Boxelder": "",
        "Bur Oak": "",
        "Butternut": "",
        "Callery Pear": "",
        "Cherry Plum": "",
        "Chinese Privet": "",
        "Common Chokecherry": "",
        "Dawn Redwood": "",
        "Eastern Red Cedar": "",
        "Eastern Redbud": "",
        "Eastern White Pine": "",
        "European Alder": "",
        "European Beech": "",
        "European Hornbeam": "",
        "Flowering Dogwood": "",
        "Freeman Maple": "",
        "Ginkgo": "",
        "Green Ash": "",
        "Hedge Maple": "",
        "Honeylocust": "",
        "Japanese Flower Crabapple": "",
        "Japanese Flowering Cherry": "",
        "Japanese Maple": "",
        "Japanese Tree Lilac": "",
        "Japanese Zelkova": "",
        "Katsura Tree": "",
        "Littleleaf Linden": "",
        "London Planetree": "",
        "Mountain Maple": "",
        "Mountain Silverbell": "",
        "Northern Hackberry": "",
        "Northern Red Oak": "",
        "Norway Maple": "",
        "Norway Spruce": "",
        "Paper Birch": "",
        "Pawpaw": "",
        "Pin Oak": "",
        "Red Maple": "",
        "River Birch": "",
        "Rock Elm": "",
        "Rose-Of-Sharon": "",
        "Scots Pine": "",
        "Siberian Elm": "",
        "Silver Linden": "",
        "Silver Maple": "",
        "Slippery Elm": "",
        "Southern Catalpa": "",
        "Staghorn Sumac": "",
        "Striped Maple": "",
        "Sugar Maple": "",
        "Swamp White Oak": "",
        "Sweet Cherry": "",
        "Sweet Crabapple": "",
        "Sweetgum": "",
        "Sycamore Maple": "",
        "Tulip Tree": "",
        "White Ash": "",
        "White Oak": "",
        "White Spruce": "",
        "Wych Elm": ""
    ]
}
